#!/bin/sh
#chkconfig: 2345 80 90
#description:auto_run
basedir=/usr/local/mysql
password=dev.2017
socketdir=/tmp/mysql.sock
pidfile=$basedir/mysqld.pid
mysqlconfdir=$basedir/my.cnf

. /etc/init.d/functions
[ $# -ne 1 ] && {
echo "USAGE:{start|stop|restart}"
exit 1
}
start(){
if [ -e $pidfile ]
then
  echo "MySQL is running."
else
  $basedir/bin/mysqld_safe --defaults-file=$mysqlconfdir  &>/dev/null &
  action  "MySQL is starting" /bin/true
  exit 0
fi
}

stop(){
if [ -e $pidfile ]
then
  $basedir/bin/mysqladmin -uroot -p$password -S $socketdir  shutdown &>/dev/null
  action "MySQL is stoping" /bin/true
else
  action "MySQL is stoping" /bin/false
  exit 1
fi
}

restart(){
  stop
  sleep 2
  start
}

case $1 in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart)
  restart
  ;;
  *)
  echo 'service accept arguments start|stop|restart'
esac
