#!/bin/bash
#chkconfig: 2345 80 90
#description:auto_run
. /etc/init.d/functions
phpdir=/usr/local/php
pidfile=$phpdir/var/run/php-fpm.pid
start(){
  if [ -f $pidfile ];then
    action "php-fpm is running now!" /bin/false
  else
    $phpdir/sbin/php-fpm -c $phpdir/etc/php.ini -y $phpdir/etc/php-fpm.conf
    action "php-fpm successful start" /bin/true
  fi

}

stop(){
  if [ -f $pidfile ];then
    kill -15 `cat $pidfile`
    action "php-fpm stopped" /bin/true
  else
    action " u cant stop,php-fpm is not  running" /bin/false
  fi
}


case $1 in 
  start)
    start;
  ;;
  stop)
    stop;
  ;;
  restart)
    stop;
    sleep 1
    start;
esac 
